### ISSUE TITLE
autostart browser does not work

### ISSUE THREAD

**Issue by simon-truhter** [EinoHR/create-ublue-image#10]
does it requires to have gh installed ahead of time?
since after i ran

`gh auth login
? What account do you want to log into? GitHub.com
? What is your preferred protocol for Git operations? HTTPS
? Authenticate Git with your GitHub credentials? Yes
? How would you like to authenticate GitHub CLI? Login with a web browser

! First copy your one-time code:`

the browser just opens and i dont have to manually click open link

i ask so dumb since its not mentioned in https://ublue.it/making-your-own/#automatic-setup
and most people will try it on a ublue install iso within a vm where nothing is setup yet.

**Comment by EinoHR** [comment]
The tool doesn't require anything installed before it being ran. Opening the browser does not work, because it tries to open a browser from inside the container, so you'll just have to copy the link manually. This is a known issue.
