### ISSUE TITLE
ask the user where to put the .key or warn them like the docs do

### ISSUE THREAD

**Issue by simon-truhter** [EinoHR/create-ublue-image#11]
i guess when time comes by more and more people will accidentally push their .key into their repo.
did not happen to me since i reversed the commit before pushing but it will happen sooner or later to someone. 

at least adding a warning would be kind that they should not push it. (it's in the docs but the script should tell it the user again) if i have missed it im sorry, maybe the warning is then not visible enough  

thanks so much for this script, it really makes it easier even when i was able to do it manually.

**Comment by EinoHR** [comment]
[The startingpoint .gitiginore](https://github.com/ublue-os/startingpoint/blob/main/.gitignore) includes `cosign.key`, which should prevent you from committing it, or atleast a git GUI from showing it as an option. But true, maybe the script could show a warning too.

**Comment by simon-truhter** [comment]
my bad it wont be added to commits when you `git add .`
