### ISSUE TITLE
Images created aren't versioned in rpm-ostree status

### ISSUE THREAD

**Issue by marinmo** [EinoHR/create-ublue-image#18]
Hello,

When using standard ublue images, output of rpm-ostree is as such;

```
  ostree-unverified-registry:ghcr.io/ublue-os/silverblue-main:38
                   Digest: sha256:9f2d4a03d1d09612d5c8b3f6a7d6be40dc3be6cabb85d96a13b3eef6f9bead52
                  Version: 38.20230513.0 (2023-05-13T16:43:33Z)
      RemovedBasePackages: package_1
          LayeredPackages: package_2
```

When using an image created through this tool, output is;

```
  ostree-unverified-registry:ghcr.io/marinmo/satellite-ublue:latest
                   Digest: sha256:f97de18e51c853e5f6b6a72555890af8fb09720cf822b9b4fcaf9908614f8532
                Timestamp: 2023-05-14T21:21:11Z
```

I'm wondering why the version (I realise this is just a concatenation of the fedora version+date+id) isn't displayed in the images created by my workflow? This seems like a slight bug to me, as comparing timestamps is less readable than the Versioning.

Thanks in advance for your consideration!

**Comment by EinoHR** [comment]
I doubt this is an issue with `create-ublue-image` but rather `ublue-os/startingpoint`, the template this tool creates. This is probably just some metadata-adding code being out of sync in startingpoint vs main.
I lack the priviliges to transfer this issue, but you should feel free to create a new one in the appropriate repo where other co-maintainers of the template repo can react to it https://github.com/ublue-os/startingpoint/issues/new
