### ISSUE TITLE
Cosign creates private key file that isn't working

### ISSUE THREAD

**Issue by Pythoner6** [EinoHR/create-ublue-image#4]
Cosign 2 (which is what's being used now in the alpine container) seems to produce a different private key file that isn't working, it's PEM header starts with:
```
-----BEGIN ENCRYPTED SIGSTORE PRIVATE KEY-----
```
compared to from previous versions:
```
-----BEGIN ENCRYPTED COSIGN PRIVATE KEY-----
```
This seemingly leads to the following error during the signing step:
```
Error: signing [ghcr.io/pythoner6/ublue-custom@sha256:8c111a115fcf428804f1a43786afbb1633d156572e954432c37ca751a7d7b291]: getting signer: reading key: invalid pem block
main.go:74: error during command execution: signing [ghcr.io/pythoner6/ublue-custom@sha256:8c111a115fcf428804f1a43786afbb1633d156572e954432c37ca751a7d7b291]: getting signer: reading key: invalid pem block
Error: Process completed with exit code 1.
```

**Comment by bsherman** [comment]
Yep... I've also run into this.

The latest cosign github action is now v3.0.1 or v3.0.2 or something ... and it does seem cosign 3 is not backward compatible with cosign 2 keys.

**Comment by EinoHR** [comment]
Update: Startingpoint has now been updated to use the same signing steps in `build.yml` as main does, and I managed to get a clean repo from the tool to build https://github.com/EinoHR/ublue-test/actions/runs/4789710128/jobs/8517904007

I think we're done here.
